server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: user-service-admin
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        - id: property-service
          uri: http://property-service:8082
          predicates:
            - Path=/api/properties/**
          filters:
            - StripPrefix=0
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=0
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
    discovery:
      enabled: false
#  web:
#    cors:
#      mappings:
#        "/api/**":
#          allowed-origins: "http://localhost:3000"
#          allowed-methods: GET, POST, PUT, DELETE, OPTIONS
#          allowed-headers: "*"
#          allow-credentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG